services:
  joke-server:
    build: .
    ports:
      - "5050:5050"
    networks:
        - joke-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - joke-network
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - joke-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  joke-network:

