version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  flaskapp:
    build: .
    ports:
      - "5001:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      - mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
