services:

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db

  flask:
    image: asixl/flask-app
    ports:
      - "9091:9091"
    environment:
      - FLASK_SERVER_PORT=9091
    depends_on:
      - mongo

  nginx:
    image: nginx
    ports:
      - "8081:8080"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
    environment:
      - FLASK_SERVER_PORT=9091

volumes:
  mongodata:

