global: 
  resolve_timeout: 5m


route:
  receiver: 'slack-default'

  routes:
   - match:
      severity: 'critical'
      receiver: 'slack-alerts-critical'

   - match:
      severity: 'high'
      receiver: 'slack-alerts-high'

receivers:
  - name: 'slack-default'
    slack_configs:
      - channel: '#alerts'
        api_url: 'https://hooks.slack.com/services/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'
        send_resolved: true

  - name: 'slack-alerts-critical'
    slack_configs:
      - channel: '#alerts-critical'
        api_url: 'https://hooks.slack.com/services/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'
        send_resolved: true

  - name: 'slack-alerts-high'
    slack_configs:
      - channel: '#alerts-high'
        api_url: 'https://hooks.slack.com/services/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'
        send_resolved: true
